const express = require('express')
const router = express.Router()
const asyncHandler = require('express-async-handler')
const bcrypt = require('bcryptjs')
const {User,validateRegisterUser,validateLoginUser}= require('../models/user.model')
const jwt = require('jsonwebtoken')